### PR TITLE
Added Split payment and Subscription to README

### PR DESCRIPTION
**Pull request by jeremiahseun**
I was searching for how to implement Split Payments. After a lot of research, I was able to make it work with this package and without an external dependency. 

So I decided to share this information so that when someone encounters this issue, this package can be the perfect fix for them.

All contributions are in the `README.md` file.

Gracias! 👌🏾

### CODE REVIEW

**Comment by Princewil** [comment]
Awesome, thanks for the info! I will check out.

**Comment by Princewil** [comment]
I went through the codes @jeremiahseun I must commend, you did a wonderful job. 

I want to know, is there a way we could give control to the additional parameters on the Split payment and other added functionality from the flutter dart end on realtime rather than hardcoding on js file?

**Comment by jeremiahseun** [comment]
Yes of course we can. 

In the paystack_interop.dart file, the paystackPopup function can have some additional parameters.

However, we have to provide the JS code as we currently have, but for split payment and for subscription.

The split payment can also work for mobile as well.

**Comment by jeremiahseun** [comment]
I think it should work this way, although I haven't tested it. @Princewil

**Comment by Princewil** [comment]
That's fine. I will go ahead and merge. We will keep working on it going forward from here.

**Pull request merged**
