### PR TITLE
Added 'PLAN' subscription feature for Mobile

### PR DESCRIPTION
**Pull request by gikwegbu**
I wrote this, but hadn't had the time to test and  make a PR. 

I included the `PLAN` option for mobile apps. I'd gone through the code and PR [jeremiahseun](https://github.com/jeremiahseun) made and noticed it's for the web alone. Correct me if i'm wrong. So please test out the implementation and let me know if it checks out.

Thanks.

### CODE REVIEW

**Comment by Princewil** [comment]
Alright Bro, I will go through it 🫡

**Comment by Princewil** [comment]
Merger completed. I will publish on pub next.

**Comment by Princewil** [comment]
Done! 
Thanks for your contribution one again.

**Comment by gikwegbu** [comment]
Glad I could help Chief. And thanks for the merge.

Ok, i'll be looking forward to the next push, as i'll be needing it on my projects :)

**Pull request merged**
