### PR TITLE
Fix missing currency parameter on web. 

### PR DESCRIPTION
**Pull request by keezysilencer**
In previous implementations, the currency value was not passed to the js_interop file. 
In this PR: I have fixed that and updated the readMe file to reflect these changes.

### CODE REVIEW

**Comment by Princewil** [comment]
Alright. Got it! 
Thanks for the update.

**Comment by keezysilencer** [comment]
> You've tested the update before the PR?

Yeah, It was tested.

**Comment by Princewil** [comment]
Oh! Cool.
I was hoping to find time to test it all this while. I will go ahead and
publish it tonight then.

**Comment by keezysilencer** [comment]
You should still make time to test it. The onClosed and callback were passing null values.

**Comment by Princewil** [comment]
Oh Wow!
I will look at it then. Thanks for the heads up

**Pull request merged**
